import {
	AppleLight,
	Bootstrap4,
	C,
	Django,
	Docker,
	FastAPI,
	Figma,
	Firebase,
	Git,
	GitHubDark,
	Go,
	GoogleCloud,
	Grafana,
	HuggingFace,
	JavaScript,
	Kubernetes,
	Linux,
	MaterialUI,
	MongoDB,
	NextJs,
	NodeJs,
	NPM,
	OCaml,
	PostgreSQL,
	Python,
	React as ReactIcon,
	Redis,
	RustDark,
	TypeScript,
	VercelDark,
	WebRTC,
} from "developer-icons";

const IconSize = 32;
export const TechLogoMap: Record<string, React.ReactElement> = {
	"Next.js": <NextJs size={IconSize} />,
	TypeScript: <TypeScript size={IconSize} />,
	JavaScript: <JavaScript size={IconSize} />,
	MUI: <MaterialUI size={IconSize} />,
	React: <ReactIcon size={IconSize} />,
	Golang: <Go size={IconSize} />,
	MongoDB: <MongoDB size={IconSize} />,
	C: <C size={IconSize} />,
	OCaml: <OCaml size={IconSize} />,
	Python: <Python size={IconSize} />,
	Rust: <RustDark size={IconSize} />,
	Docker: <Docker size={IconSize} />,
	Bootstrap: <Bootstrap4 size={IconSize} />,
	Django: <Django size={IconSize} />,
	FastAPI: <FastAPI size={IconSize} />,
	GoogleCloud: <GoogleCloud size={IconSize} />,
	Node: <NodeJs size={IconSize} />,
	Vercel: <VercelDark size={IconSize} />,
	Firebase: <Firebase size={IconSize} />,
	PostgreSQL: <PostgreSQL size={IconSize} />,
	Redis: <Redis size={IconSize} />,
	Figma: <Figma size={IconSize} />,
	Linux: <Linux size={IconSize} />,
	Apple: <AppleLight size={IconSize} />,
	Grafana: <Grafana size={IconSize} />,
	HuggingFace: <HuggingFace size={IconSize} />,
	Kubernetes: <Kubernetes size={IconSize} />,
	NPM: <NPM size={IconSize} />,
	Github: <GitHubDark size={IconSize} />,
	Git: <Git size={IconSize} />,
	WebRTC: <WebRTC size={IconSize} />,
};
export default TechLogoMap;
